<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit36733c203fcaec90d8df0af88b04eb7a
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'Apaapi\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Apaapi\\' => 
        array (
            0 => __DIR__ . '/..' . '/jakiboy/apaapi/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit36733c203fcaec90d8df0af88b04eb7a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit36733c203fcaec90d8df0af88b04eb7a::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
